export const ELASTIC_GEOMETRY = Object.freeze({
  tau: Math.PI * 2,
  segmentCount: 28,
});

const BASE_TUNING = Object.freeze({
  frameIntervalMs: 16.67,
  frameDtMinMs: 8,
  frameDtMaxMs: 34,
  toneVisibilityThreshold: 0.001,
  pointerIdleThreshold: 0.015,
  pointerIdleWindowMs: 80,
  pointerMomentumDivisor: 35,
  pointerDecayActive: 0.94,
  pointerDecayIdle: 0.86,
  centerSpring: 0.032,
  centerDamping: 0.82,
  scaleSpring: 0.087,
  scaleDamping: 0.78,
  rimSpring: 0.24,
  rimSmooth: 0.18,
  rimDamping: 0.74,
  rimImpulseSpread: 3,
  rimInflationRatio: 0.45,
  rimRadiusMinScale: 0.5,
  rimRadiusMaxScale: 1.9,
  baseRadiusRatio: 0.038,
  minRadius: 24,
  maxRadius: 60,
  mobileRadiusScale: 0.86,
  fixedRadius: null,
  circleGap: 0,
  minScale: 0.62,
  maxScale: 2.46,
  hoverRangeScale: 2.15,
  hoverBoostBase: 1.12,
  hoverBoostOffset: 0.72,
  hoverMomentumGain: 1.7,
  compressionToScale: 0.28,
  compressionMaxScaleLoss: 0.42,
  neighborDistanceScale: 2.28,
  collisionImpulseScale: 0.12,
  collisionElasticBase: 0.2,
  collisionElasticGain: 0.8,
  edgeBandScale: 0.38,
  edgeImpulseBase: 0.65,
  edgeImpulseMomentumGain: 2.1,
  snapThresholdScale: 0.24,
  snapThresholdMomentumGain: 0.08,
  snapReleaseBase: 1.45,
  snapReleaseMomentumGain: 3.2,
  snapLaunchBase: 1.4,
  snapLaunchMomentumGain: 4.8,
  snapScaleVelocityGain: 0.09,
  snapScaleVelocityBase: 1,
  snapCooldown: 16,
  snapSpread: 4,
  snapSpreadDivisor: 5,
  maxRimPullScale: 0.42,
  maxRimPushScale: -0.24,
  attractRangeScale: 5.8,
  attractBase: 0.22,
  attractMomentumGain: 0.5,
  elasticFalloffRangeScale: 9.2,
  minElasticInfluence: 0.07,
  farSpringBoost: 1.75,
  farDampingBoost: 0.11,
  centerDampingClampMin: 0.62,
  centerDampingClampMax: 0.95,
  gradationMaxGray: 221,
  gradationEase: 0.06,
  gradationInfluenceGate: 0.08,
  gradationPropagationGain: 0.95,
  gradationToneBase: 0.9,
  gradationToneMomentumGain: 0.35,
  maskZoomGain: 0.92,
  maskInflationZoomGain: 0.26,
  maskInfluenceZoomGain: 0.34,
  maskNeighborScaleGain: 0.24,
  maskInfluenceGate: 0.08,
});

const REDUCED_MOTION_OVERRIDES = Object.freeze({
  centerSpring: 0.046,
  centerDamping: 0.78,
  scaleSpring: 0.11,
  scaleDamping: 0.72,
  rimSpring: 0.3,
  rimSmooth: 0.22,
  rimDamping: 0.68,
  baseRadiusRatio: 0.042,
  hoverBoostBase: 0.76,
  hoverMomentumGain: 1.2,
  attractBase: 0.16,
  attractMomentumGain: 0.28,
  gradationEase: 0.09,
});

const MODE_TUNING = Object.freeze({
  normal: Object.freeze({
    fixedRadius: null,
    circleGap: 0,
  }),
  gradation: Object.freeze({
    fixedRadius: null,
    circleGap: 0,
  }),
  fine: Object.freeze({
    fixedRadius: 10,
    circleGap: 8,
  }),
  mask: Object.freeze({
    fixedRadius: null,
    circleGap: 0,
  }),
});

export function createElasticConfig({ mode, reducedMotion }) {
  return {
    ...BASE_TUNING,
    ...(reducedMotion ? REDUCED_MOTION_OVERRIDES : {}),
    ...(MODE_TUNING[mode] ?? MODE_TUNING.normal),
  };
}
